---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-12-21T12:59:34.470131+01:00"
  name: flux-fundamentals
  namespace: erikkelder
spec:
  interval: 10m0s
  ref:
    branch: main
  secretRef:
    name: flux-fundamentals
  timeout: 1m0s
  url: https://github.com/ekelder/gitops-fundamentals-exercises.git
